### ISSUE TITLE
support for video input ?

### ISSUE THREAD

**Issue by pmahan00** [vladmandic/movenet#2]
Hi, is there implementation or support to run the multipose on a video stream ?

**Comment by vladmandic** [comment]
my main library <https://github.com/vladmandic/human> fully supports `movenet`, this is just a reference conversion/implementation

**Comment by pmahan00** [comment]
thank you . I was hoping to run `movenet multipose` in a mobile phone , was thinking of using `react-expo` Do you have any suggestion if they also work on phone ? Great work btw , it is super comprehensive

**Comment by vladmandic** [comment]
it all depends on the phone - if its strong enough (modern phones are definitely ok, but some low-end ones are just not).

then its the question of computational backend:   
- `wasm` and `webgl` work, but that requires a webapp (yes, you can do a pwa style app for mobile).  
- for fully optimized `react-expo`, it requires `@tensorflow/tfjs-react-native` backend which is a bit out-of-date (tensorflow team hasn't updated it for over a year).  
 
plus i don't test with react-native, so issues are possible - i'm willing to work to solve it, but i dont have an android dev environment at the moment so it would be a bit longer.

for example, `human` library currently has one open issue exactly for react-native which i've believe i've solved, but need a user confirmation.

**Comment by pmahan00** [comment]
Hi thanks , for the info. I actually tried once to run a p5js application on the phone . The results were quite bad even with movenet but it was never optimised ( even for front camera). Could you point me to the issue with react native

**Comment by vladmandic** [comment]
sure, its <https://github.com/vladmandic/human/issues/327>

**Comment by pmahan00** [comment]
thanks , a bit of digging let me to these post : https://github.com/tensorflow/tfjs-examples/blob/master/react-native/pose-detection/App.tsx however i have still not managed to run it on react-expo . Will this be some good help ? (not tried on front facing camera )

**Comment by vladmandic** [comment]
like i said, i think i fixed it already, but need a user to test and confirm - thats why issue is still open.  
if there are any remaining issues, i can tackle it as they occure.
